# Start with a base image containing Node.js runtime
FROM node:alpine

# Set the working directory in the Docker image
WORKDIR /app

## copy over package.json
COPY package.json .

# Install any necessary dependencies
RUN npm install

# Copy everything from the current directory to the PWD(Present Working Directory) inside the container
COPY . .

# Expose port 3000 to the outside
EXPOSE 3000

# Run the application
CMD ["npm", "start"]
