# Build stage
FROM node:16 AS build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ARG REACT_APP_API_URL
ENV REACT_APP_API_URL=${REACT_APP_API_URL}
#uncomment for testing on staging site
ENV PUBLIC_URL=/admin
RUN npm run build

# Production stage
FROM nginx AS production-stage
#uncomment for testing on staging site
COPY default.conf /etc/nginx/conf.d/default.conf
COPY --from=build-stage /app/build /usr/share/nginx/html
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]